#!/usr/bin/env bash

set -euo pipefail

# Sync all Dokka HTML outputs into docs-website/static/api for local viewing
# This script is safe to run repeatedly. It will mirror outputs per-module.

REPO_ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
DEST_DIR="${REPO_ROOT_DIR}/docs-website/static/api"

echo "Repository root: ${REPO_ROOT_DIR}"
echo "Destination directory: ${DEST_DIR}"

mkdir -p "${DEST_DIR}"
touch "${DEST_DIR}/.gitkeep" || true

# Detect if rsync is available for efficient syncing
if command -v rsync >/dev/null 2>&1; then
  SYNC_WITH_RSYNC=true
else
  SYNC_WITH_RSYNC=false
fi

sync_dir() {
  local src_dir="$1"
  local dest_dir="$2"
  
  # Check if source directory has any content
  if [ ! -d "$src_dir" ] || [ -z "$(ls -A "$src_dir" 2>/dev/null)" ]; then
    echo "  Skipping empty or non-existent directory: $src_dir"
    return 0
  fi
  
  mkdir -p "$dest_dir"
  if [ "${SYNC_WITH_RSYNC}" = true ]; then
    rsync -a --delete "$src_dir"/ "$dest_dir"/
  else
    # Fallback without rsync: destructive copy
    rm -rf "$dest_dir"/*
    cp -R "$src_dir"/* "$dest_dir"/ 2>/dev/null || true
  fi
  echo "  Successfully synced to: $dest_dir"
}

echo "Scanning for Dokka HTML outputs..."

# 1) Subproject Dokka outputs: */build/dokka/html
mapfile -t SUBMODULE_DOKKA_DIRS < <(find "${REPO_ROOT_DIR}" -type d -path "*/build/dokka/html" 2>/dev/null || true)

if [ ${#SUBMODULE_DOKKA_DIRS[@]} -gt 0 ]; then
  echo "Found ${#SUBMODULE_DOKKA_DIRS[@]} submodule Dokka directories"
  for dokka_dir in "${SUBMODULE_DOKKA_DIRS[@]}"; do
    module_dir="$(dirname "$(dirname "$(dirname "$dokka_dir")")")" # up from html -> dokka -> build -> module
    module_name="$(basename "$module_dir")"
    target="${DEST_DIR}/${module_name}"
    echo "Syncing module '${module_name}' from ${dokka_dir} -> ${target}"
    sync_dir "$dokka_dir" "$target"
  done
else
  echo "No submodule Dokka directories found (*/build/dokka/html)."
fi

# 2) Root multi-module Dokka output (per current Dokka config): build/docs/html
ROOT_MULTI_DIR="${REPO_ROOT_DIR}/build/docs/html"
if [ -d "${ROOT_MULTI_DIR}" ]; then
  echo "Syncing root multi-module docs from ${ROOT_MULTI_DIR} -> ${DEST_DIR}/root"
  sync_dir "${ROOT_MULTI_DIR}" "${DEST_DIR}/root"
else
  echo "Root multi-module docs directory not found at ${ROOT_MULTI_DIR} (skipping)."
fi

# 3) Legacy/alternative root output (some tasks produce build/dokka/html)
LEGACY_ROOT_DIR="${REPO_ROOT_DIR}/build/dokka/html"
if [ -d "${LEGACY_ROOT_DIR}" ]; then
  echo "Syncing legacy root docs from ${LEGACY_ROOT_DIR} -> ${DEST_DIR}/root"
  sync_dir "${LEGACY_ROOT_DIR}" "${DEST_DIR}/root"
fi

# Prevent GitHub Pages from treating underscores as special, useful if served elsewhere
touch "${DEST_DIR}/.nojekyll" || true

echo "Done. Local API docs are available under: ${DEST_DIR}"

# Generate an index.html that lists all modules (and root) for convenient navigation
INDEX_FILE="${DEST_DIR}/index.html"
{
  echo "<!DOCTYPE html>"
  echo "<html lang=\"en\">"
  echo "<head>"
  echo "  <meta charset=\"UTF-8\" />"
  echo "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />"
  echo "  <title>API Reference</title>"
  echo "  <style>body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Ubuntu,Cantarell,\"Noto Sans\",\"Helvetica Neue\",Arial,\"Apple Color Emoji\",\"Segoe UI Emoji\";max-width:960px;margin:32px auto;padding:0 16px;line-height:1.6}h1{margin-bottom:0.25rem}ul{padding-left:1.25rem}code{background:#f6f7f9;padding:2px 6px;border-radius:4px}</style>"
  echo "</head>"
  echo "<body>"
  echo "  <h1>API Reference</h1>"
  echo "  <p>Choose a module below to view its Dokka-generated documentation:</p>"
  echo "  <ul>"
  # Prefer showing 'root' multi-module docs first if present
  if [ -d "${DEST_DIR}/root" ]; then
    echo "    <li><a href=\"./root/index.html\"><strong>All Modules</strong> (multi-module index)</a></li>"
  fi
  # List all directories in DEST_DIR except special files/dirs
  for d in "${DEST_DIR}"/*/ ; do
    [ -d "$d" ] || continue
    name="$(basename "$d")"
    if [ "$name" = "root" ]; then
      continue
    fi
    # Skip hidden dirs
    case "$name" in .* ) continue;; esac
    echo "    <li><a href=\"./$name/index.html\">$name</a></li>"
  done
  echo "  </ul>"
  echo "  <p><small>This page is auto-generated by <code>sync-dokka-to-static-api.sh</code>.</small></p>"
  echo "</body>"
  echo "</html>"
} > "$INDEX_FILE"
echo "Wrote index: ${INDEX_FILE}"


