/*
 * Copyright 2025 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See See https://github.com/openMF/kmp-project-template/blob/main/LICENSE
 */
package kpt.core.database

import androidx.room3.Room
import androidx.sqlite.driver.bundled.BundledSQLiteDriver
import kotlinx.coroutines.Dispatchers
import kotlin.test.AfterTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class AppDatabaseTest {

    private var database: AppDatabase? = null

    @AfterTest
    fun teardown() {
        database?.close()
    }

    @Test
    fun inMemoryDatabaseCanBeCreated() {
        database = Room.inMemoryDatabaseBuilder<AppDatabase>()
            .setDriver(BundledSQLiteDriver())
            .setQueryCoroutineContext(Dispatchers.IO)
            .build()

        assertNotNull(database)
    }

    @Test
    fun databaseExposeAlertDao() {
        database = Room.inMemoryDatabaseBuilder<AppDatabase>()
            .setDriver(BundledSQLiteDriver())
            .setQueryCoroutineContext(Dispatchers.IO)
            .build()

        assertNotNull(database!!.alertDao)
    }

    @Test
    fun databaseExposeInterestRateSeriesDao() {
        database = Room.inMemoryDatabaseBuilder<AppDatabase>()
            .setDriver(BundledSQLiteDriver())
            .setQueryCoroutineContext(Dispatchers.IO)
            .build()

        assertNotNull(database!!.interestRateSeriesDao)
    }

    @Test
    fun databaseVersionIsCurrent() {
        // Bumped to 12 in the v11→v12 change that added the `framework_write_conflicts` table
        // (MutationGateway conflict inbox) with a matching AutoMigration(11→12) + 12.json export.
        // Update this constant when bumping AppDatabase.VERSION so the guardrail stays meaningful.
        // The full in-place upgrade chain is now closed: AutoMigration hops exist for every step up to
        // 12 (incl. the 10→11 `cloud_todos` add that #274 originally omitted), so a v10 device upgrades
        // cleanly to v12.
        assertEquals(12, AppDatabase.VERSION)
    }

    @Test
    fun databaseNameIsCorrect() {
        // Fork-unique, appId-derived (regenerated by syncForkConfig). DATABASE_NAME
        // delegates to the single source of truth, DatabaseConfig.NAME.
        assertEquals(DatabaseConfig.NAME, AppDatabase.DATABASE_NAME)
    }
}
