# deployment/desktop/mac-app-store/screenshots/lane.rb
# macOS screenshot pipeline — AI-generated screenshots.
#
# Screenshots are generated by Claude intelligence (via /release) and placed
# directly into the metadata screenshots directory as PNG files. No Compose
# Desktop UI tests, AWT Robot, or Gradle task infrastructure required.
#
# Lanes:
#   upload_macos_screenshots   — upload screenshots to Mac App Store via deliver
#   macos_screenshots          — alias for upload_macos_screenshots

MAC_SCREENSHOTS_PATH = File.expand_path("../metadata/screenshots", __dir__).freeze
MAC_METADATA_PATH    = File.expand_path("../metadata", __dir__).freeze
MAC_PRIMARY_LOCALE   = "en-GB".freeze

platform :mac do
  desc "Upload macOS screenshots to Mac App Store via deliver"
  lane :upload_macos_screenshots do |options|
    setup_ci_if_needed

    cfg = FastlaneConfig::IosConfig::BUILD_CONFIG

    deliver(
      username:               ENV["FASTLANE_APPLE_ID"] || options[:apple_id_email],
      team_id:                ENV["APPLE_TEAM_ID"],
      metadata_path:          MAC_METADATA_PATH,
      screenshots_path:       MAC_SCREENSHOTS_PATH,
      primary_locale:         MAC_PRIMARY_LOCALE,
      skip_binary_upload:     true,
      skip_metadata:          true,
      skip_screenshots:       false,
      overwrite_screenshots:  true,
      force:                  true,
    )

    UI.success("✅ macOS screenshots uploaded to Mac App Store")
  end

  desc "Upload macOS screenshots (generation is handled by /release)"
  lane :macos_screenshots do |options|
    upload_macos_screenshots(options)
  end
end
