/*
 * Copyright 2026 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See https://github.com/openMF/kmp-project-template/blob/main/LICENSE
 */

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.MapProperty
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import org.gradle.work.DisableCachingByDefault
import java.io.File

/**
 * Generates `cmp-ios/Configs/{variant}.xcconfig` for every flavor × build-type
 * combination declared in the `kmpFlavors {}` DSL.
 *
 * ## Single source of truth chain
 *
 *   KMPFlavorsConventionPlugin (DSL)
 *     └─ this task reads flavors + buildTypes at execution time
 *           └─ writes cmp-ios/Configs/{variant}.xcconfig
 *                 └─ xcconfig uses $(APP_BUNDLE_ID) + $(TEAM_ID)
 *                       └─ resolved at Xcode build time from Config.xcconfig
 *                             └─ Config.xcconfig generated by ./gradlew syncForkConfig
 *                                   └─ source: libs.versions.toml (appId / iosTeamId)
 *
 * ## Auto-wiring
 *
 * Registered by [KMPFlavorsConventionPlugin] and wired to iOS compilation tasks so
 * xcconfigs regenerate automatically whenever the Gradle flavor DSL changes.
 * Run manually: `./gradlew :cmp-shared:generateIosFlavorXcconfigs`
 *
 * ## What each xcconfig contains
 *
 * Only structural values — no behavioral flavor data (BASE_URL, credentials, feature
 * flags). Those belong in KMP `BuildConfig` generated by the kmpFlavors plugin itself.
 *
 *   KMPF_VARIANT              — variant name; consumed by FRAMEWORK_SEARCH_PATHS in pbxproj
 *   PRODUCT_BUNDLE_IDENTIFIER — $(APP_BUNDLE_ID) + combined bundle suffix
 *   DEVELOPMENT_TEAM          — $(TEAM_ID) from Config.xcconfig (resolved at Xcode build time)
 */
@DisableCachingByDefault(because = "Fast codegen task; output depends on DSL state resolved at execution time")
abstract class GenerateIosFlavorXcconfigsTask : DefaultTask() {

    /** flavor name → iOS bundleIdSuffix (e.g. "demo" → ".demo", "prod" → ""). */
    @get:Input
    abstract val flavorBundleSuffixes: MapProperty<String, String>

    /** build-type name → iOS bundleIdSuffix (usually "" — build types rarely have iOS suffixes). */
    @get:Input
    abstract val buildTypeBundleSuffixes: MapProperty<String, String>

    /** cmp-ios/Configs/ directory. */
    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val flavors    = flavorBundleSuffixes.get()
        val buildTypes = buildTypeBundleSuffixes.get()
        val dir        = outputDir.get().asFile.also { it.mkdirs() }

        // Remove stale per-variant xcconfigs (handles renamed / deleted flavors).
        // iOSApp.xcconfig is the static umbrella — never delete it.
        dir.listFiles { f -> f.name.endsWith(".xcconfig") && f.name != "iOSApp.xcconfig" }
            ?.forEach { it.delete() }

        for ((flavor, flavorSuffix) in flavors.entries.sortedBy { it.key }) {
            for ((buildType, buildTypeSuffix) in buildTypes.entries.sortedBy { it.key }) {
                val variant      = "$flavor${buildType.replaceFirstChar { it.uppercase() }}"
                val combined     = flavorSuffix + buildTypeSuffix
                val bundleExpr   = if (combined.isEmpty()) "\$(APP_BUNDLE_ID)"
                                   else "\$(APP_BUNDLE_ID)$combined"

                File(dir, "$variant.xcconfig").writeText(buildXcconfig(flavor, buildType, variant, bundleExpr))
                logger.lifecycle("generateIosFlavorXcconfigs: wrote $variant.xcconfig  (bundle: $bundleExpr)")
            }
        }
    }

    private fun buildXcconfig(flavor: String, buildType: String, variant: String, bundleExpr: String) =
        """
        |// kmp-product-flavors — flavor: $flavor  build-type: $buildType
        |// Auto-generated — do not edit manually.
        |// Re-generate: ./gradlew :cmp-shared:generateIosFlavorXcconfigs
        |// Source: KMPFlavorsConventionPlugin.kt DSL. Identity (APP_BUNDLE_ID / TEAM_ID): libs.versions.toml → syncForkConfig → Config.xcconfig.
        |//
        |// This file is the Xcode build configuration's base config (wired directly in
        |// project.pbxproj — NOT via a $(CONFIGURATION) umbrella include, which Xcode
        |// does not expand). It owns the per-flavor identity below and pulls in the
        |// matching CocoaPods settings via the #include? at the bottom.
        |
        |KMPF_VARIANT = $variant
        |PRODUCT_BUNDLE_IDENTIFIER = $bundleExpr
        |DEVELOPMENT_TEAM = ${'$'}(TEAM_ID)
        |
        |// CocoaPods — per-configuration link/framework settings. Optional (#include?)
        |// so a fresh clone builds before `pod install` runs (cmp-ios/Pods/ is gitignored
        |// and regenerated by CI). CocoaPods lowercases the configuration name for the
        |// xcconfig filename (demoDebug → demodebug); macOS/APFS is case-insensitive.
        |#include? "../Pods/Target Support Files/Pods-iosApp/Pods-iosApp.${variant.lowercase()}.xcconfig"
        |
        """.trimMargin()
}
