/*
 * Copyright 2026 Mifos Initiative
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See https://github.com/openMF/kmp-project-template/blob/main/LICENSE
 */

/* =================================================================================
 *  DO NOT EDIT THIS FILE TO ADD CONSUMER-SPECIFIC FLAVORS.
 *  This file is SYNCED from kmp-project-template into every downstream consumer
 *  app via sync-dirs.sh. Any local edits here will be OVERWRITTEN on the next
 *  sync.
 *
 *  To add consumer-specific flavors / dimensions / overrides, create:
 *      build-logic/convention/src/main/kotlin/local/LocalFlavors.kt
 *
 *  That local/ directory is excluded from sync-dirs.sh and survives every sync.
 *  See docs/FLAVORS_EXTENSION.md for the pattern.
 * ================================================================================= */

import com.mobilebytelabs.kmpflavors.KmpFlavorExtension
import com.mobilebytelabs.kmpflavors.KmpFlavorPlugin
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.kotlin.dsl.configure

/**
 * Convention plugin that wires kmp-product-flavors with the BASE flavor contract
 * every downstream consumer app inherits:
 *
 * - tier: demo (default — demo credentials for testers / public demo APK) and
 *   prod (real customers).
 * - buildType: debug (default — debuggable), staging, release.
 *
 * Consumer apps extend this contract by creating
 * build-logic/convention/src/main/kotlin/local/LocalFlavors.kt — see
 * LocalFlavorsLoader for the hook and docs/FLAVORS_EXTENSION.md for examples.
 */
class KMPFlavorsConventionPlugin : Plugin<Project> {
    override fun apply(target: Project) {
        with(target) {
            pluginManager.apply(KmpFlavorPlugin::class.java)

            extensions.configure<KmpFlavorExtension> {
                buildConfigPackage.set("org.openmf.kmptemplate")
                buildConfigClassName.set("FlavorConfig")
                enableBuildTypes.set(true)

                // Single base dimension — consumer apps may add more.
                flavorDimensions {
                    register("tier") { priority.set(0) }
                }

                // Base flavors. Every consumer app gets these two.
                flavors {
                    register("demo") {
                        dimension.set("tier")
                        isDefault.set(true)
                        applicationIdSuffix.set(".demo")
                        bundleIdSuffix.set(".demo")
                        buildConfigField("Boolean", "IS_DEMO_BUILD", "true")
                        buildConfigField("String", "BASE_URL", "\"https://demo.openmf.org\"")
                        buildConfigField("String", "DEMO_USERNAME", "\"demo\"")
                        buildConfigField("String", "DEMO_PASSWORD", "\"demo\"")
                    }
                    register("prod") {
                        dimension.set("tier")
                        buildConfigField("Boolean", "IS_DEMO_BUILD", "false")
                        buildConfigField("String", "BASE_URL", "\"https://api.openmf.org\"")
                        buildConfigField("String", "DEMO_USERNAME", "\"\"")
                        buildConfigField("String", "DEMO_PASSWORD", "\"\"")
                    }
                }

                buildTypes {
                    register("debug") {
                        isDefault.set(true)
                        isDebuggable.set(true)
                        applicationIdSuffix.set(".debug")
                        buildConfigField("Boolean", "ENABLE_LOGGING", "true")
                        buildConfigField("Boolean", "SHOW_DEBUG_OVERLAY", "true")
                        buildConfigField("String", "LOG_TAG", "\"KMPTemplate-DEBUG\"")
                    }
                    register("staging") {
                        isDebuggable.set(false)
                        applicationIdSuffix.set(".staging")
                        buildConfigField("Boolean", "ENABLE_LOGGING", "true")
                        buildConfigField("Boolean", "SHOW_DEBUG_OVERLAY", "false")
                        buildConfigField("String", "LOG_TAG", "\"KMPTemplate-STAGING\"")
                    }
                    register("release") {
                        isDebuggable.set(false)
                        isMinifyEnabled.set(true)
                        buildConfigField("Boolean", "ENABLE_LOGGING", "false")
                        buildConfigField("Boolean", "SHOW_DEBUG_OVERLAY", "false")
                        buildConfigField("String", "LOG_TAG", "\"KMPTemplate\"")
                    }
                }

                // === Consumer-extension hook ======================================
                // Probes for local.LocalFlavors.apply(ext, project). No-op when
                // the consumer hasn't created a local override.
                LocalFlavorsLoader.applyIfPresent(this, target)
                // ==================================================================
            }
        }
    }
}
