import org.gradle.api.DefaultTask
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import org.gradle.kotlin.dsl.register

/**
 * Registers the `syncForkConfig` task on whichever project applies this plugin.
 *
 * Apply from root build.gradle.kts:
 *   plugins { id("org.convention.fork.sync-config") }
 *
 * Then run:
 *   ./gradlew syncForkConfig
 */
class SyncForkConfigPlugin : Plugin<Project> {
    override fun apply(target: Project) {
        val catalog = target.extensions
            .getByType(org.gradle.api.artifacts.VersionCatalogsExtension::class.java)
            .named("libs")

        val appId          = catalog.findVersion("appId").get().requiredVersion
        val appDisplayName = catalog.findVersion("appDisplayName").get().requiredVersion
        val iosTeamId      = catalog.findVersion("iosTeamId").get().requiredVersion
        val projectName    = catalog.findVersion("projectName").get().requiredVersion

        target.tasks.register<SyncForkConfigTask>("syncForkConfig") {
            group       = "fork"
            description = "Sync fork identity from libs.versions.toml to all platform config files."

            this.appId.set(appId)
            this.appDisplayName.set(appDisplayName)
            this.iosTeamId.set(iosTeamId)
            this.projectName.set(projectName)

            xcconfigFile.set(target.file("cmp-ios/Configuration/Config.xcconfig"))
            localPropertiesFile.set(target.file("local.properties"))
            gradlePropertiesFile.set(target.file("gradle.properties"))
        }
    }
}

abstract class SyncForkConfigTask : DefaultTask() {

    @get:Input abstract val appId:          Property<String>
    @get:Input abstract val appDisplayName: Property<String>
    @get:Input abstract val iosTeamId:      Property<String>
    @get:Input abstract val projectName:    Property<String>

    @get:OutputFile abstract val xcconfigFile:        RegularFileProperty
    @get:OutputFile abstract val localPropertiesFile:  RegularFileProperty
    @get:OutputFile abstract val gradlePropertiesFile: RegularFileProperty

    @TaskAction
    fun sync() {
        val id      = appId.get()
        val name    = appDisplayName.get()
        val team    = iosTeamId.get()
        val project = projectName.get()

        // ── iOS xcconfig ─────────────────────────────────────────────────────────
        xcconfigFile.get().asFile.writeText(
            "// Fork identity — generated by ./gradlew syncForkConfig from libs.versions.toml\n" +
            "// To change: edit libs.versions.toml, then re-run syncForkConfig.\n" +
            "APP_BUNDLE_ID = $id\nAPP_NAME = $name\nTEAM_ID = $team\n"
        )
        logger.lifecycle("syncForkConfig: wrote ${xcconfigFile.get().asFile.name}")

        // ── local.properties (Fastlane bridge — gitignored) ──────────────────────
        val lp = localPropertiesFile.get().asFile
        val props = java.util.Properties()
        if (lp.exists()) lp.inputStream().use(props::load)
        props["fork.app.id"]           = id
        props["fork.app.display.name"] = name
        props["fork.project.name"]     = project
        lp.outputStream().use { props.store(it, "Generated by syncForkConfig — do not edit manually") }
        logger.lifecycle("syncForkConfig: updated local.properties")

        // ── gradle.properties (settings.gradle.kts bridge) ───────────────────────
        val gp     = gradlePropertiesFile.get().asFile
        val gpText = if (gp.exists()) gp.readText() else ""
        gp.writeText(
            if (gpText.contains("fork.project.name="))
                gpText.replace(Regex("fork\\.project\\.name=.*"), "fork.project.name=$project")
            else
                gpText.trimEnd() + "\nfork.project.name=$project\n"
        )
        logger.lifecycle("syncForkConfig: updated gradle.properties fork.project.name=$project")
    }
}
