import org.gradle.api.DefaultTask
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import org.gradle.kotlin.dsl.register
import org.gradle.work.DisableCachingByDefault
import java.io.File

/**
 * Registers the `syncForkConfig` task on whichever project applies this plugin.
 *
 * Apply from root build.gradle.kts:
 *   plugins { id("org.convention.fork.sync-config") }
 *
 * Then run:
 *   ./gradlew syncForkConfig
 */
class SyncForkConfigPlugin : Plugin<Project> {
    override fun apply(target: Project) {
        val catalog = target.extensions
            .getByType(org.gradle.api.artifacts.VersionCatalogsExtension::class.java)
            .named("libs")

        val appId          = catalog.findVersion("appId").get().requiredVersion
        val appDisplayName = catalog.findVersion("appDisplayName").get().requiredVersion
        val iosTeamId      = catalog.findVersion("iosTeamId").get().requiredVersion
        val projectName    = catalog.findVersion("projectName").get().requiredVersion

        target.tasks.register<SyncForkConfigTask>("syncForkConfig") {
            group       = "fork"
            description = "Sync fork identity from libs.versions.toml to all platform config files."

            // syncForkConfig is a manual on-demand task: the source-of-truth
            // for icons is `branding/icons/` content, which Gradle's input
            // tracking doesn't watch (marked @Internal for opt-in semantics).
            // Always re-run — the task is cheap and the user explicitly invoked
            // it because they expect a fresh sync.
            outputs.upToDateWhen { false }

            this.appId.set(appId)
            this.appDisplayName.set(appDisplayName)
            this.iosTeamId.set(iosTeamId)
            this.projectName.set(projectName)

            xcconfigFile.set(target.file("cmp-ios/Configuration/Config.xcconfig"))
            localPropertiesFile.set(target.file("local.properties"))
            gradlePropertiesFile.set(target.file("gradle.properties"))

            // Fork-icon source-of-truth + per-platform destinations.
            iconBrandingDir.set(target.layout.projectDirectory.dir("branding/icons"))
            iosAppIconDir.set(target.layout.projectDirectory.dir("cmp-ios/iosApp/Assets.xcassets/AppIcon.appiconset"))
            jsResourcesDir.set(target.layout.projectDirectory.dir("cmp-web/src/jsMain/resources"))
            wasmJsResourcesDir.set(target.layout.projectDirectory.dir("cmp-web/src/wasmJsMain/resources"))
            desktopIconsDir.set(target.layout.projectDirectory.dir("cmp-desktop/icons"))
            androidResDir.set(target.layout.projectDirectory.dir("cmp-android/src/main/res"))
            projectRootDir.set(target.layout.projectDirectory)
        }
    }
}

@DisableCachingByDefault(because = "Writes to local.properties which is gitignored and machine-specific")
abstract class SyncForkConfigTask : DefaultTask() {

    @get:Input abstract val appId:          Property<String>
    @get:Input abstract val appDisplayName: Property<String>
    @get:Input abstract val iosTeamId:      Property<String>
    @get:Input abstract val projectName:    Property<String>

    @get:OutputFile abstract val xcconfigFile:        RegularFileProperty
    @get:OutputFile abstract val localPropertiesFile:  RegularFileProperty
    @get:OutputFile abstract val gradlePropertiesFile: RegularFileProperty

    // Icon copy I/O. iconBrandingDir is @Internal — its presence is optional
    // (missing dir = skip step, template defaults preserved), and Gradle's
    // up-to-date check would force the dir to exist if declared @InputDirectory.
    // Platform destination dirs are @Internal because they're per-file outputs
    // resolved at task-action time, not whole-dir outputs.
    @get:Internal abstract val iconBrandingDir:    DirectoryProperty
    @get:Internal abstract val iosAppIconDir:      DirectoryProperty
    @get:Internal abstract val jsResourcesDir:     DirectoryProperty
    @get:Internal abstract val wasmJsResourcesDir: DirectoryProperty
    @get:Internal abstract val desktopIconsDir:    DirectoryProperty
    @get:Internal abstract val androidResDir:      DirectoryProperty
    @get:Internal abstract val projectRootDir:     DirectoryProperty

    @TaskAction
    fun sync() {
        val id      = appId.get()
        val name    = appDisplayName.get()
        val team    = iosTeamId.get()
        val project = projectName.get()

        // ── iOS xcconfig ─────────────────────────────────────────────────────────
        xcconfigFile.get().asFile.writeText(
            "// Fork identity — generated by ./gradlew syncForkConfig from libs.versions.toml\n" +
            "// To change: edit libs.versions.toml (appId / appDisplayName / iosTeamId), then re-run syncForkConfig.\n" +
            "APP_BUNDLE_ID = $id\nAPP_NAME = $name\nTEAM_ID = $team\n"
        )
        logger.lifecycle("syncForkConfig: wrote ${xcconfigFile.get().asFile.name}")

        // ── local.properties (Fastlane bridge — gitignored) ──────────────────────
        val lp = localPropertiesFile.get().asFile
        val props = java.util.Properties()
        if (lp.exists()) lp.inputStream().use(props::load)
        props["fork.app.id"]           = id
        props["fork.app.display.name"] = name
        props["fork.project.name"]     = project
        lp.outputStream().use { props.store(it, "Generated by syncForkConfig — do not edit manually") }
        logger.lifecycle("syncForkConfig: updated local.properties")

        // ── gradle.properties (settings.gradle.kts bridge) ───────────────────────
        val gp     = gradlePropertiesFile.get().asFile
        val gpText = if (gp.exists()) gp.readText() else ""
        gp.writeText(
            if (gpText.contains("fork.project.name="))
                gpText.replace(Regex("fork\\.project\\.name=.*"), "fork.project.name=$project")
            else
                gpText.trimEnd() + "\nfork.project.name=$project\n"
        )
        logger.lifecycle("syncForkConfig: updated gradle.properties fork.project.name=$project")

        // ── Fork icons (binary, per-platform) ────────────────────────────────────
        copyForkIcons()
    }

    /**
     * Copies fork-specific app-icon files from [iconBrandingDir] to canonical
     * platform locations. Each mapping is optional: missing source = no-op
     * (template default preserved). See `branding/icons/README.md` for the file
     * contract.
     */
    private fun copyForkIcons() {
        val src = iconBrandingDir.get().asFile
        if (!src.exists()) {
            logger.lifecycle("syncForkConfig: branding/icons/ not present — skipping icon copy (template defaults preserved)")
            return
        }

        val projectRoot = projectRootDir.get().asFile

        // Per-platform single-file mappings: (sourceName, destDir, destName).
        val mappings = listOf(
            Triple("ios.png",             iosAppIconDir.get().asFile,      "AppIcon.png"),
            Triple("web-favicon.ico",     jsResourcesDir.get().asFile,     "favicon.ico"),
            Triple("web-favicon.ico",     wasmJsResourcesDir.get().asFile, "favicon.ico"),
            Triple("desktop-macos.icns",  desktopIconsDir.get().asFile,    "ic_launcher.icns"),
            Triple("desktop-windows.ico", desktopIconsDir.get().asFile,    "ic_launcher.ico"),
            Triple("desktop-linux.png",   desktopIconsDir.get().asFile,    "ic_launcher.png"),
        )
        var copied = 0
        for ((srcName, dstDir, dstName) in mappings) {
            val from = File(src, srcName)
            if (!from.exists()) continue
            dstDir.mkdirs()
            val to = File(dstDir, dstName)
            from.copyTo(to, overwrite = true)
            logger.lifecycle("syncForkConfig: copied branding/icons/$srcName → ${to.relativeTo(projectRoot)}")
            copied++
        }

        // Android: optional pre-built res tree at branding/icons/android/.
        val androidSrc = File(src, "android")
        if (androidSrc.isDirectory && androidSrc.list()?.isNotEmpty() == true) {
            val androidDst = androidResDir.get().asFile
            androidSrc.copyRecursively(androidDst, overwrite = true)
            logger.lifecycle("syncForkConfig: copied branding/icons/android/ → ${androidDst.relativeTo(projectRoot)}/ (recursive)")
            copied++
        } else {
            logger.lifecycle("syncForkConfig: branding/icons/android/ not present — Android adaptive icons require Android Studio's Image Asset Studio (one-time, commit the result). See branding/icons/README.md.")
        }

        if (copied == 0) {
            logger.lifecycle("syncForkConfig: branding/icons/ contained no recognised files — template defaults preserved")
        }
    }
}
