/*
 * Generated by ./gradlew syncForkConfig from appId in gradle/libs.versions.toml.
 * Fork-unique on-disk DB filename; every platform DatabaseModule reads NAME.
 */
package kpt.core.database

object DatabaseConfig {
    const val NAME = "org_mifos_kmp_template.db"
}
