name: Sync CMP Directories
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  sync-directories:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: dev

      - name: Setup Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add upstream remote and fetch
        run: |
          git remote add upstream https://github.com/openMF/kmp-project-template.git || true
          git fetch upstream || exit 1

      - name: Check upstream/dev exists
        run: |
          if ! git rev-parse --verify upstream/dev >/dev/null 2>&1; then
            echo "Error: upstream/dev branch does not exist"
            exit 1
          fi

      - name: Create and checkout temporary branch
        run: |
          TEMP_BRANCH="temp-sync-branch-${{ github.run_number }}"
          git checkout -b "$TEMP_BRANCH" upstream/dev || exit 1
          echo "TEMP_BRANCH=$TEMP_BRANCH" >> $GITHUB_ENV

      - name: Sync directories
        run: |
          DIRS=(
            "cmp-android"
            "cmp-desktop"
            "cmp-ios"
            "cmp-web"
            "cmp-shared"
            "build-logic"
            "fastlane"
            "scripts"
            "config"
            ".github"
            ".run"
          )
          
          FILES=(
            "Gemfile"
            "Gemfile.lock"
            "ci-prepush.bat"
            "ci-prepush.sh"
          )
          
          git checkout dev
          
          # Sync directories
          for dir in "${DIRS[@]}"; do
            if [ ! -d "$dir" ]; then
              echo "Creating $dir..."
              mkdir -p "$dir"
            fi
            echo "Syncing $dir..."
            git checkout "${{ env.TEMP_BRANCH }}" -- "$dir" || exit 1
          done
          
          # Sync files
          for file in "${FILES[@]}"; do
            echo "Syncing $file..."
            git checkout "${{ env.TEMP_BRANCH }}" -- "$file" || true
          done

      - name: Clean up temporary branch
        if: always()
        run: git branch -D "${{ env.TEMP_BRANCH }}" || true

      - name: Check for changes
        id: check_changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check_changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: Sync directories and files from upstream"
          title: "chore: Sync directories and files from upstream"
          body: |
            Automated sync of directories and files from upstream repository.
            
            Changes included in this sync:
            
            Directories:
            - cmp-android
            - cmp-desktop
            - cmp-ios
            - cmp-web
            - build-logic
            - fastlane
            - scripts
            - config
            - .github
            - .run
            
            Files:
            - Gemfile
            - Gemfile.lock
            - ci-prepush.bat
            - ci-prepush.sh
            
            Workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          branch: sync-dirs-${{ github.run_number }}
          delete-branch: true
          labels: |
            sync
            automated pr
          base: dev